version: '3.8'
services:
  php-apache-environment:
    container_name: 'docker-laravel'
    build: 
      context: ./php/
      dockerfile: Dockerfile
    # working_dir: /var/www/html/
    volumes:
      - ./php/src/:/var/www/html
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      # - ./php/src/:/var/www/
    ports:
      - 8000:80
    networks:
      - docker-laravel-network

  db:
    container_name: docker-laravel-db
    # platform: linux/x86_64
    # image: mysql:8.0
    image: mariadb:10.5.8
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
    ports:
      - "9906:3306"
    networks:
      - docker-laravel-network
networks:
  docker-laravel-network:
    driver: bridge
